### ISSUE TITLE
CircleCI should not allow concurrent deployments

### ISSUE THREAD

**Issue by allthesignals** [NYCPlanning/labs-work-planning#10]
Right now CircleCI concurrently runs the deployment steps along with anything else. Either _no_ Circle builds should run concurrently or (preferably) no deployment steps should be allowed to run concurrently. Perhaps if there's a way to queue individual steps? 

In any case this can create enormous slowdown for our dokku server. It might be even be preferable for Dokku to disallow concurrent deployments on its end so that resources are depleted. Thoughts @chriswhong ?

**Comment by chriswhong** [comment]
I think the bigger risk/annoyance is that circleci builds will fail if a dokku app is already being built (rapid successive commits to develop, for example, would cause this situation).  

Re: your point above, have we actually observed "enormous slowdown" on the dokku server?  I don't think these builds are that intensive, and definitely shouldn't be happening often enough to cause an issue with service, but correct me if I am wrong.

**Comment by allthesignals** [comment]
@chriswhong yes when I hotfixed many apps at once the other day. It was probably an isolated incident but CPU was running 100% all because of GitHub commits.
